image: docker pull registry.nulana.com/bobrnor/battleship-builder:latest

stages:
  - test
  - build

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo -e "Host git.nulana.com\n\tHostName git.nulana.com\n\tPort 2221\n\tUser git\n\n" >> ~/.ssh/config
  - export CURRENT_BUILD_PATH=$(pwd)
  - rm -rf $HOME/gopath
  - mkdir -p $HOME/gopath/src/git.nulana.com/bobrnor/battleship-client
  - export GOPATH=$HOME/gopath
  - export PATH=$PATH:$GOPATH/bin
  - echo $PATH
  - go version
  - go env
  - which go

test:
  stage: test
  script:
    - cp -R $CURRENT_BUILD_PATH/* $HOME/gopath/src/git.nulana.com/bobrnor/battleship-client
    - cd $HOME/gopath
    - go get ...
    - cd $HOME/gopath/src/git.nulana.com/bobrnor/battleship-client
    - go test ./...

build:
  stage: build
  script:
    - cp -R $CURRENT_BUILD_PATH/* $HOME/gopath/src/git.nulana.com/bobrnor/battleship-client
    - cd $HOME/gopath
    - go get ...
    - cd $HOME/gopath/src/git.nulana.com/bobrnor/battleship-client/build
    - GOOS=linux GOARCH=amd64 go build ../battleship.go
    - docker build -t registry.nulana.com/bobrnor/battleship-client -f Dockerfile .
    - docker login registry.nulana.com -u danil@nulana.com -p "$REGISTRY_PASSWORD"
    - docker push registry.nulana.com/bobrnor/battleship-client:latest
    - docker logout registry.nulana.com
